language: python

python:
  - "3.6"
  
cache: pip

install:
  - pip install awscli

before_script:
 - wget https://github.com/spf13/hugo/releases/download/v0.17/hugo_0.17_Linux-64bit.tar.gz
 - tar -xvf hugo_0.17_Linux-64bit.tar.gz

script:
 - ./hugo_0.17_linux_amd64/hugo_0.17_linux_amd64
 
after_success:
 - aws s3 rm s3://artemnikitin.com --recursive
 - aws s3 cp public/ s3://artemnikitin.com --recursive
 - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_ID --paths "/*"
