language: go
go: 
 - 1.7.3

install:
 - go get github.com/artemnikitin/s3-tool
 - go get github.com/artemnikitin/cci

before_script:
 - wget https://github.com/spf13/hugo/releases/download/v0.17/hugo_0.17_Linux-64bit.tar.gz
 - tar -xvf hugo_0.17_Linux-64bit.tar.gz

script:
 - ./hugo_0.17_linux_amd64/hugo_0.17_linux_amd64
 - s3-tool upload -bucket artemnikitin.com -region eu-west-1 -key / -path $GOPATH/src/github.com/artemnikitin/artemnikitin.com/public
 
after_success:
 - s3-tool download -bucket qwe-v323-dsdasd-1eewe-xcsscs-121a -key prod.json -path $GOPATH/src/github.com/artemnikitin/artemnikitin.com -region eu-west-1
 - cci -config $GOPATH/src/github.com/artemnikitin/artemnikitin.com/prod.json
