language: go
go: 
 - 1.7.1

install:
 - go get github.com/artemnikitin/s3-tool

before_script:
 - wget https://github.com/spf13/hugo/releases/download/v0.17/hugo_0.17_Linux-64bit.tar.gz
 - tar -xvf hugo_0.17_Linux-64bit.tar.gz

script:
 - ./hugo_0.17_linux_amd64/hugo_0.17_linux_amd64
 
after_success:
 - s3-tool upload -bucket artemnikitin.com -region eu-west-1 -key / -path $GOPATH/src/github.com/artemnikitin/artemnikitin.com/public
